<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>
<?php
$baseHelper = $this->helper('ET\Base\Helper\Data');
$baseUrl = $baseHelper->getBaseUrl();
$ishome = $baseHelper->getIsHome();
$showHome = $baseHelper->getConfigValue('header_section/megamenu/show_home_link');
?>
<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php if ($showHome) { ?>
            <li class = "level0 level-top <?php if ($ishome) { ?> active <?php } ?>">
                <a class = "level-top" href = "<?php echo $baseUrl; ?>">
                    <?php echo __('Home');
                    ?>
                </a>
            </li>
        <?php } ?>
        <?= /* @noEscape */ $_menuHtml?>
        <?= $block->getChildHtml() ?>
    </ul>
</nav>
<script type="text/javascript" xml="space">
    require(['jquery','Magento_Customer/js/customer-data'], function ($,customerData) {
        var cart = customerData.get('cart');
        var lastCount = cart().summary_count;
        cart.subscribe(function (updatedCart) {
            if (updatedCart.summary_count > lastCount && updatedCart.summary_count > 0) {
                setTimeout(function () {
                    $('[data-block="minicart"]').find('.action.showcart').trigger('click');
                }, 1000);
            }
            lastCount = updatedCart.summary_count;
        });
    });
</script>