<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ? : 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php
$helper = $this->helper('Hidden\ShopkartLite\Helper\Data');
$baseUrl = $helper->getBaseUrl();
$ishome = $helper->getIsHome();

$showHome = $helper->getConfigValue('shopkartlitesettings/navigation_settings/enable');
?>
<nav class="navigation" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php if ($showHome) { ?>
            <li class = "level0 level-top <?php if ($ishome) { ?> active <?php } ?>">
                <a class = "level-top" href = "<?php echo $baseUrl; ?>">
                    <?php echo __('Home');
                    ?>
                </a>
            </li>
        <?php } ?>
        <?php /* @escapeNotVerified */ echo $_menu; ?>
    </ul>
</nav>
<script type="text/javascript" xml="space">
    require(['jquery','Magento_Customer/js/customer-data'], function ($,customerData) {
        var cart = customerData.get('cart');
        var lastCount = cart().summary_count;
        cart.subscribe(function (updatedCart) {
            if (updatedCart.summary_count > lastCount && updatedCart.summary_count > 0) {
                setTimeout(function () {
                    $('[data-block="minicart"]').find('.action.showcart').trigger('click');
                }, 1000);
            }
            lastCount = updatedCart.summary_count;
        });
    });
</script>