<div class="contact-info">
    <h2>Contact Information</h2>

    <p><strong>Business Name:</strong> Overxero</p>

    <p><strong>Address:</strong><br>
        575 Lundy Ln<br>
        Hudson, WI 54016<br>
        United States</p>

    <p><strong>Phone:</strong><br>
        <a href="tel:+17153861700">+1 715-386-1700</a></p>

    <p><strong>Email:</strong><br>
        <a href="mailto:support@overxero.com">support@overxero.com</a></p>

    <p><strong>Business Hours:</strong><br>
        Mon - Fri: 9:00 AM – 6:00 PM (EST)</p>
</div>
<style>
    @media screen and (min-width: 768px) {
        .contact-index-index .form.contact{
            display: inline-block;
        }
        .contact-index-index .contact-info{
            display: inline-block;
            margin-left: 100px;
        }

    }
</style>
