<div class="contact-info">
    <h2>Contact Information</h2>

    <p><strong>Business Name:</strong> Mysignbox</p>

    <p><strong>Address:</strong><br>
        133 Lanier Dr #1310<br>
        Statesboro, GA 30458<br>
        United States</p>

    <p><strong>Phone:</strong><br>
        <a href="tel:+19124864437">+1 (912) 486-4437</a></p>

    <p><strong>Email:</strong><br>
        <a href="mailto:support@mysignbox.com">support@mysignbox.com</a></p>

    <p><strong>Business Hours:</strong><br>
        Mon - Fri: 9:00 AM – 6:00 PM (EST)</p>
</div>
<style>
    @media screen and (min-width: 768px) {
        .contact-index-index .form.contact{
            display: inline-block;
        }
        .contact-index-index .contact-info{
            display: inline-block;
            margin-left: 100px;
        }

    }
</style>
