<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
$helper = $this->helper('Hidden\ShopkartLite\Helper\Data');
$customCss = $helper->getConfigValue('shopkartlitesettings/customcss/custom_css');
if ($customCss != '') {
    ?>
    <style>
    <?php
    echo $customCss;
    ?>
    </style>
<?php }
?>
<style>
    .page-footer {
        background: #000 !important;
    }
    .opc-payment-additional .form-discount button {
        padding-top: 5px;
    }
</style>